# THIS CONFIG FILE WILL BE EMBEDDED IN THE BINARY.
# For user configuration, use "config.yaml".

checkers:
  webhost:
    popular:
      - name: Google
        filter: host("www.google.com")
      - name: Google Gstatic
        filter: host("www.gstatic.com")
      - name: YouTube Web
        filter: host("www.youtube.com")
      - name: YouTube Image
        filter: host("i.ytimg.com")
      - name: X (ex. Twitter)
        filter: host("x.com")
      - name: Discord
        filter: host("discord.com")
      - name: Github
        filter: host("github.com")
      - name: Telegram Web
        filter: host("web.telegram.org")
      - name: Telegram Api
        filter: host("api.telegram.org")
      - name: Facebook
        filter: host("www.facebook.com")
      - name: WhatsApp Web
        filter: host("web.whatsapp.com")
      - name: Instagram
        filter: host("www.instagram.com")
      - name: LinkedIn
        filter: host("www.linkedin.com")
    infra:
      - name: Cloudflare
        filter: org("cloudflare")
      - name: Akamai
        filter: org("akamai")
      - name: Amazon
        filter: as(16509)
      - name: Fastly
        filter: org("fastly")
      - name: Oracle
        filter: org("oracle")
      - name: Contabo
        filter: org("contabo")
      - name: CDN77 / DataCamp
        filter: org("datacamp")
      - name: DigitalOcean
        filter: org("digitalocean")
        count: 2
      - name: Hetzner:de
        filter: org("hetzner") && country("de")
      - name: Hetzner:fi
        filter: org("hetzner") && country("fi")
      - name: OVH
        filter: as(16276)
        count: 2
      - name: Gcore
        filter: as(199524)
      - name: FT/BuyVM
        filter: as(53667)
      - name: Google Cloud
        filter: as(396982)
      - name: Melbicom
        filter: org("melbikomas")
      - name: Scaleway
        filter: org("scaleway")
      - name: Vultr
        filter: as(20473)
      - name: Microsoft/Azure
        filter: as(8075)
    workers: 8
    tcp-conn-timeout: 3s
    tls-handshake-timeout: 3s
    tcp-read-timeout: 15s
    tcp-write-timeout: 15s
    tcp-write-buf: 4096
    tcp-read-buf: 4096
    tcp1620-n-bytes: 65536
    http-static-headers:
      Accept: "*/*"
      Content-Type: application/octet-stream
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36
    table-max-visible-rows: 20

  cidrwhitelist:
    timeout: 15s
    whitelisted:
      - https://max.ru/
      - https://ya.ru/
      - https://vk.ru/
    regular:
      - https://github.com/
      - https://ru.wikipedia.org/
      - https://www.google.com/

  dns:
    table-max-visible-rows: 10

    leak:
      timeout: 15s
      times: 4
      workers: 4
      parent-domain: dns4.browserleaks.net
      label-len: 12
      label-alpha: abcdefghijkmnopqrstuvwyz0123456789

    resolve:
      plain-opt:
        timeout: 10s
        workers: 5

      doh-opt:
        timeout: 10s
        workers: 5
        path: /dns-query
        http-static-headers:
          Content-Type: application/dns-message

      targets:
        - host: www.youtube.com
          filter: org("google")
        - host: x.com
          filter: org("cloudflare") || org("fastly")
        - host: discord.com
          filter: org("cloudflare")
        - host: www.facebook.com
          filter: org("facebook")
        - host: www.instagram.com
          filter: org("facebook")
        - host: www.linkedin.com
          filter: org("cloudflare") || org("microsoft")
        - host: currenttime.tv
          filter: org("akamai")

      providers:
        - name: Cloudflare DNS
          plain:
            - 1.1.1.1:53
            - 1.0.0.1:53
          doh:
            filter: org("cloudflare")
            hosts:
              - cloudflare-dns.com
              - dns.cloudflare.com
              - one.one.one.one

        - name: Google DNS
          plain:
            - 8.8.8.8:53
            - 8.8.4.4:53
          doh:
            filter: org("google")
            hosts:
              - dns.google

        - name: OpenDNS
          plain:
            - 208.67.222.222:53
            - 208.67.220.220:53
          doh:
            filter: org("opendns")
            hosts:
              - dns.opendns.com

        - name: AdGuard DNS
          plain:
            - 94.140.14.14:53
            - 94.140.15.15:53
          doh:
            filter: org("adguard")
            hosts:
              - dns.adguard-dns.com

        - name: Yandex DNS
          plain:
            - 77.88.8.8:53
            - 77.88.8.1:53

  whoami:
    timeout: 15s

# Internal modules

subnetfilter:
  workers: 8

webhostfarm:
  workers: 8
  tcp-conn-timeout: 3s
  tls-handshake-timeout: 3s

inetlookup:
  ripe-api-url: https://stat.ripe.net/data/
  yandex-api-url: https://yandex.ru/internet/api/v0/

inetlookup-geolitecsv:
  cidr-as: ./data/geolite/cidr-as.csv
  cidr-country: ./data/geolite/cidr-country.csv
  geonameid-country: ./data/geolite/geonameid-country.csv

httputil:
  browser-headers:
    Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36

updater:
  enabled: true
  period: 24h
  self-ts-file: self-ts
  inetlookup-ts-file: inetlookup-ts
  timeout: 120s
  root-dir: ./data
  self:
    owner: hyperion-cs
    repo: dpi-checkers
  geolite:
    dir: ./geolite
    owner: Loyalsoldier
    repo: geoip
    branch: release
    cidr-as:
      from: GeoLite2-ASN-Blocks-IPv4.csv
      to: cidr-as.csv
    cidr-country:
      from: GeoLite2-Country-Blocks-IPv4.csv
      to: cidr-country.csv
    geonameid-country:
      from: GeoLite2-Country-Locations-en.csv
      to: geonameid-country.csv
